@startuml projet_bap

class Application {
    - root: tk.Tk
    - interface: InterfaceUtilisateur
    - logique: LogiqueMetier
    + __init__()
}

class InterfaceUtilisateur {
    - master: tk.Tk
    + canvas: tk.Canvas
    + toolbar_frame: tk.Frame
    + bouton_noeud: tk.Button
    + bouton_arc: tk.Button
    + bouton_effacer: tk.Button
    + bouton_sauvegarder: tk.Button
    + bouton_charger: tk.Button
    + __init__(master: tk.Tk)
}

class LogiqueMetier {
    - canvas: tk.Canvas
    - noeuds: dict
    - arcs: list
    - debut_arc: int
    - arc_temporaire: int
    - mode: str
    + __init__(canvas: tk.Canvas)
    + set_mode_noeud()
    + set_mode_arc()
    + is_mode_arc() : bool
    + is_mode_noeud() : bool
    + clic_canvas(event)
    + ajouter_noeud(event)
    + dessiner_arc(event)
    + trouver_noeud_plus_proche(x: int, y: int) : int
    + afficher_arcs()
    + afficher_noeuds()
    + sauvegarder()
    + charger_graphe()
    + effacer_graphe()
}

Application "1" -- "1" InterfaceUtilisateur : utilise
Application "1" -- "1" LogiqueMetier : utilise
InterfaceUtilisateur "1" -- "1" tk.Canvas : contient
LogiqueMetier "1" -- "1" tk.Canvas : utilise


@enduml